// ATLAS v2 tool action schema definitions (pure data).
//
// The raw, undecorated ATLAS action surface. Per the catalog contract this
// holds pure data only. The merge with generated descriptor schemas
// (atlasDescriptorSchemaForAction), the surfacing filters, and the assembled
// ATLAS_TOOL_DEFS / SURFACED_ATLAS_TOOL_DEFS live in the integrations
// tool-descriptors module, which imports ATLAS_TOOL_DEFS_RAW from here.

const ATLAS_SYMBOL_ID_PATTERN = "^[0-9a-f]{64}:[0-9]+$";

export const ATLAS_TOOL_DEFS_RAW = Object.freeze({
  "query": {
    type: "function",
    name: "atlas_query",
    description: "Gateway. Compact native ATLAS v2 retrieval wrapper for symbol, slice, context, diff/risk, and exact memory surface/get actions.",
    parameters: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["symbol.search", "symbol.card", "symbol.overview", "slice.build", "slice.refresh", "slice.spillover.get", "edit.plan", "file.read", "context", "context.summary", "review.delta", "review.analyze", "review.risk", "repo.status", "repo.quality", "memory.surface", "memory.get"], description: "ATLAS action to route through this gateway." },
      },
      required: ["action"],
      additionalProperties: true,
    },
  },
  "code": {
    type: "function",
    name: "atlas_code",
    description: "Gateway. Compact native ATLAS v2 code-inspection wrapper for skeleton, hot-path, area survey, edit planning, and gated raw-window actions.",
    parameters: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["code.skeleton", "code.lens", "code.window", "code.survey", "edit.plan", "file.read"], description: "ATLAS code action to route through this gateway." },
      },
      required: ["action"],
      additionalProperties: true,
    },
  },
  "repo": {
    type: "function",
    name: "atlas_repo",
    description: "Gateway. Compact native ATLAS v2 repository/operations wrapper for lifecycle, diagnostics, policy, usage, and SCIP actions.",
    parameters: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["info", "action.search", "manual", "repo.register", "repo.status", "repo.quality", "index.refresh", "policy.get", "policy.set", "usage.stats", "runtime.execute", "runtime.queryOutput", "scip.ingest"], description: "ATLAS repository action to route through this gateway." },
      },
      required: ["action"],
      additionalProperties: true,
    },
  },
  "agent": {
    type: "function",
    name: "atlas_agent",
    description: "Gateway. Compact native ATLAS v2 agent wrapper for context, feedback, live buffers, and memory actions.",
    parameters: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["context", "context.summary", "agent.feedback", "agent.feedback.query", "buffer.push", "buffer.checkpoint", "buffer.status", "memory.store", "memory.feedback"], description: "ATLAS agent action to route through this gateway." },
      },
      required: ["action"],
      additionalProperties: true,
    },
  },
  "action.search": {
    type: "function",
    name: "atlas_action_search",
    description: "Discovery. Search the native ATLAS v2 action catalog for the right tool/action to call.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search terms such as symbol, memory, policy, risk, or raw window." },
        namespace: { type: "string", description: "Optional namespace filter such as repo, symbol, code, memory, policy, or agent." },
        limit: { type: "integer", description: "Maximum actions to return." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "manual": {
    type: "function",
    name: "atlas_manual",
    description: "Discovery. Return a compact native ATLAS v2 API manual filtered by query or explicit actions.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Filter manual entries by search terms." },
        actions: { type: "array", items: { type: "string" }, description: "Explicit action names to include." },
        limit: { type: "integer", description: "Maximum manual entries to return." },
        includeSchemas: { type: "boolean", description: "Include full JSON schemas. Defaults to compact parameter summaries." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "workflow": {
    type: "function",
    name: "atlas_workflow",
    description: "Workflow. Execute multiple native ATLAS v2 actions and data transforms in one call with $0/$stepId references, budget handling, and optional trace output.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional repository identifier shared across workflow steps." },
        steps: {
          type: "array",
          description: "Ordered workflow steps. Use action for ATLAS actions or fn for camelCase action aliases/data transforms.",
          items: {
            type: "object",
            properties: {
              id: { type: "string", description: "Optional step id for later references like $search.items[0].symbolId." },
              fn: { type: "string", description: "CamelCase ATLAS function alias or transform name such as dataPick." },
              action: { type: "string", description: "Canonical ATLAS action name such as symbol.search or code.skeleton." },
              args: { type: "object", description: "Step arguments. Exact string refs like $0.items[0].symbolId are resolved before execution." },
              maxResponseTokens: { type: "integer", description: "Optional per-step response token cap." },
            },
            additionalProperties: false,
          },
        },
        budget: {
          type: "object",
          properties: {
            maxTotalTokens: { type: "integer" },
            maxSteps: { type: "integer" },
            maxDurationMs: { type: "integer" },
          },
          additionalProperties: false,
        },
        onError: { type: "string", enum: ["continue", "stop"], description: "Whether to continue after a failed step. Defaults to continue." },
        defaultMaxResponseTokens: { type: "integer", description: "Default response cap for steps without maxResponseTokens." },
        onlyFinalResult: { type: "boolean", description: "Strip intermediate results from the returned payload." },
        trace: {
          type: "object",
          properties: {
            level: { type: "string", enum: ["summary", "verbose"] },
            includeResolvedArgs: { type: "boolean" },
            maxPreviewTokens: { type: "integer" },
          },
          additionalProperties: false,
        },
        dryRun: { type: "boolean", description: "Validate steps and references without executing." },
      },
      required: ["steps"],
      additionalProperties: false,
    },
  },
  "info": {
    type: "function",
    name: "atlas_info",
    description: "Diagnostics. Return native ATLAS v2 runtime, repository, storage, view freshness, ledger, and optional policy details.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional stable repository identifier." },
        includePolicy: { type: "boolean", description: "Include the effective native ATLAS v2 policy." },
        includeCounts: { type: "boolean", description: "Include small ledger row-count diagnostics when a ledger is open." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "repo.register": {
    type: "function",
    name: "atlas_repo_register",
    description: "Lifecycle. Register the current repository with ATLAS v2, creating the ledger and an empty main view when needed.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional stable repository identifier." },
        repoRoot: { type: "string", description: "Absolute repository root override." },
        branch: { type: "string", description: "Baseline ledger branch. Defaults to the configured merge target." },
        buildEmptyView: { type: "boolean", description: "Create an empty main view on cold repositories. Defaults to true." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "repo.status": {
    type: "function",
    name: "atlas_repo_status",
    description: "Bookkeeping/version anchor. Fetch ATLAS repository status and latest ledger version identifiers; this does not count as meaningful ATLAS retrieval by itself.",
    parameters: {
      type: "object",
      properties: {
        detail: { type: "string", description: "Detail level: minimal, standard, or full." },
        surfaceMemories: { type: "boolean", description: "Surface relevant memories when enabled in ATLAS." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "index.refresh": {
    type: "function",
    name: "atlas_index_refresh",
    description: "Lifecycle. Refresh the ATLAS v2 ledger and materialized view for the repository, either fully or for a bounded list of paths.",
    parameters: {
      type: "object",
      properties: {
        mode: { type: "string", enum: ["smart", "full", "incremental"], description: "Refresh mode. smart chooses incremental when paths are supplied, otherwise full." },
        paths: { type: "array", items: { type: "string" }, description: "Canonical repo-relative paths for incremental refresh." },
        branch: { type: "string", description: "Ledger branch to refresh. Defaults to the configured merge target." },
        wait: { type: "boolean", description: "Reserved for async schedulers; embedded v2 currently returns the warm result." },
        async: { type: "boolean", description: "Request async operation semantics. Embedded v2 records the request but currently completes synchronously." },
        includeDiagnostics: { type: "boolean", description: "Include phase timings and bounded progress events in the response." },
        operationId: { type: "string", description: "Optional caller-provided operation id for progress correlation." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "repo.overview": {
    type: "function",
    name: "atlas_repo_overview",
    description: "Discovery overview. Fetch token-efficient ATLAS repository summaries, indexed coverage, directory summaries, and hotspots.",
    parameters: {
      type: "object",
      properties: {
        level: { type: "string", enum: ["stats", "directories", "hotspots", "graph", "full"], description: "Detail level: stats, directories, hotspots, graph, or full." },
        includeHotspots: { type: "boolean", description: "Include hotspot analysis when supported." },
        directories: { type: "array", items: { type: "string" }, description: "Relative directories to focus on." },
        maxDirectories: { type: "integer", description: "Maximum directories to include." },
        maxExportsPerDirectory: { type: "integer", description: "Maximum exports to include per directory." },
        ifNoneMatch: { type: "string", description: "Optional ETag for conditional fetch." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "repo.quality": {
    type: "function",
    name: "atlas_repo_quality",
    description: "Diagnostics. Inspect ATLAS v2 index quality: view freshness, edge resolution, parser health, embeddings, and feedback gaps.",
    parameters: {
      type: "object",
      properties: {
        probeTreeSitter: { type: "boolean", description: "Attempt to load observed tree-sitter grammars and report failures." },
        feedbackLimit: { type: "integer", description: "Maximum feedback aggregates to inspect for quality hints." },
        halfLifeDays: { type: "number", description: "Optional recency decay half-life in days for feedback weights." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "buffer.push": {
    type: "function",
    name: "atlas_buffer_push",
    description: "Live editor overlay. Push an unsaved buffer into ATLAS v2 retrieval without writing it to disk.",
    parameters: {
      type: "object",
      properties: {
        filePath: { type: "string", description: "Canonical repository-relative path for the buffer." },
        content: { type: "string", description: "Full buffer contents." },
        sessionId: { type: "string", description: "Optional editor/session namespace." },
        version: { type: "integer", description: "Optional editor buffer version." },
        eventType: { type: "string", enum: ["open", "change", "save", "close", "checkpoint"], description: "Editor event that produced this buffer update." },
        language: { type: "string", description: "Editor language id, when available." },
        dirty: { type: "boolean", description: "Whether the editor buffer has unsaved changes." },
        timestamp: { type: "string", description: "Editor event timestamp. Defaults to receipt time." },
        cursor: {
          type: "object",
          properties: {
            line: { type: "integer" },
            column: { type: "integer" },
          },
          additionalProperties: false,
        },
        selections: {
          type: "array",
          items: {
            type: "object",
            properties: {
              startLine: { type: "integer" },
              startColumn: { type: "integer" },
              endLine: { type: "integer" },
              endColumn: { type: "integer" },
            },
            additionalProperties: false,
          },
        },
      },
      required: ["filePath", "content"],
      additionalProperties: false,
    },
  },
  "buffer.checkpoint": {
    type: "function",
    name: "atlas_buffer_checkpoint",
    description: "Live editor overlay. Clear an ATLAS v2 buffer overlay after it has been saved, or optionally write it to disk.",
    parameters: {
      type: "object",
      properties: {
        filePath: { type: "string", description: "Canonical repository-relative path for the buffer." },
        sessionId: { type: "string", description: "Optional editor/session namespace." },
        writeToDisk: { type: "boolean", description: "Write overlay contents to disk before clearing." },
        clear: { type: "boolean", description: "Clear the overlay even when disk contents differ." },
      },
      required: ["filePath"],
      additionalProperties: false,
    },
  },
  "buffer.status": {
    type: "function",
    name: "atlas_buffer_status",
    description: "Live editor overlay. Inspect active ATLAS v2 unsaved buffers for the repository.",
    parameters: {
      type: "object",
      properties: {
        filePath: { type: "string", description: "Optional canonical repository-relative path filter." },
        sessionId: { type: "string", description: "Optional editor/session namespace." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "symbol.search": {
    type: "function",
    name: "atlas_symbol_search",
    description: "Discovery. Search ATLAS's indexed repo-defined symbol graph for relevant project symbols by name, concept, or semantic hint when you do not yet know the symbol ID. Do not use this to resolve language/runtime/library functions such as date, gmdate, password_verify, json_decode, Math.floor, or console.log; use body/code lookup to find repo code that calls them.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Symbol search query." },
        limit: { type: "integer", description: "Maximum number of results to return." },
        semantic: { type: "boolean", description: "Enable semantic reranking when supported." },
        scope: { type: "string", enum: ["name", "body", "either"], description: "Search symbol names, symbol-body identifier tokens, or both. Default either." },
        entities: {
          type: "array",
          items: { type: "string", enum: ["symbols", "feedback"] },
          description: "Entity families to include. Default symbols; feedback is returned in a separate entities list.",
        },
      },
      required: ["query"],
      additionalProperties: false,
    },
  },
  "symbol.card": {
    type: "function",
    name: "atlas_symbol_card",
    description: "Iris Rung 1 (~100 tokens). Fetch one compact symbol card by symbolId or symbolRef: signature, summary, callers/callees, relationship metrics, and location.",
    parameters: {
      type: "object",
      properties: {
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Opaque ATLAS symbol ID returned by symbol.search, symbol.card, slice.build, code.skeleton, or code.lens results. Do not construct this from file paths or names." },
        symbolRef: {
          type: "object",
          description: "Fallback lookup when you do not have a symbolId. Prefer symbol.search first; use this for a concrete name plus optional file.",
          properties: {
            name: { type: "string", description: "Symbol name to resolve." },
            file: { type: "string", description: "Optional repository-relative file path containing the symbol." },
            kind: { type: "string", description: "Optional symbol kind hint." },
            exportedOnly: { type: "boolean", description: "Prefer exported symbols only when possible." },
          },
          required: ["name"],
          additionalProperties: false,
        },
        ifNoneMatch: { type: "string", description: "Optional ETag for conditional fetch." },
        minCallConfidence: { type: "number", description: "Minimum call-confidence threshold." },
        includeResolutionMetadata: { type: "boolean", description: "Include ATLAS resolution metadata." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "symbol.cards": {
    type: "function",
    name: "atlas_symbol_cards",
    description: "Iris Rung 1, batched. Fetch multiple compact symbol cards in one call by symbolIds or symbolRefs, with per-item errors so a single bad reference does not fail the batch.",
    parameters: {
      type: "object",
      properties: {
        symbolIds: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs returned by ATLAS results. Do not construct these from file paths or names." },
        symbolRefs: {
          type: "array",
          description: "Fallback lookups when you do not have symbolIds. Each is a concrete name plus optional file/kind.",
          items: {
            type: "object",
            properties: {
              name: { type: "string", description: "Symbol name to resolve." },
              file: { type: "string", description: "Optional repository-relative file path containing the symbol." },
              kind: { type: "string", description: "Optional symbol kind hint." },
              exportedOnly: { type: "boolean", description: "Prefer exported symbols only when possible." },
            },
            required: ["name"],
            additionalProperties: true,
          },
        },
        minCallConfidence: { type: "number", description: "Minimum call-confidence threshold." },
        includeResolutionMetadata: { type: "boolean", description: "Include ATLAS resolution metadata." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "slice.build": {
    type: "function",
    name: "atlas_slice_build",
    description: "Task scoping. Build a bounded ATLAS slice for a task or known entry symbols before escalating into code evidence. TaskText-only requests use semantic entry discovery when embeddings are active and lexical entry discovery otherwise; provide entrySymbols or editedFiles for tighter precision.",
    parameters: {
      type: "object",
      properties: {
        taskText: { type: "string", description: "Natural-language task description." },
        semantic: { type: "boolean", description: "Enable semantic/vector entry discovery when configured. Defaults on for taskText when semantic dispatch is enabled." },
        taskType: { type: "string", enum: ["debug", "review", "implement", "explain"], description: "Optional task type for feedback-aware ranking." },
        entrySymbols: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs returned by ATLAS results. Do not construct these from file paths or names." },
        editedFiles: { type: "array", items: { type: "string" }, description: "Relative edited file paths." },
        stackTrace: { type: "string", description: "Optional stack trace for debugging context." },
        failingTestPath: { type: "string", description: "Optional failing test path." },
        cardDetail: { type: "string", description: "ATLAS card detail level." },
        adaptiveDetail: { type: "boolean", description: "Enable adaptive detail selection." },
        knownCardEtags: { type: "object", additionalProperties: { type: "string" }, description: "Optional map of symbolId to card ETag already held by the agent; matching cards return lightweight refs." },
        ifNoneMatch: { type: "string", description: "Optional slice ETag for conditional fetch; matching slices return notModified metadata only." },
        wireFormat: { type: "string", enum: ["standard", "compact", "agent", "packed"], description: "Response wire format. Use packed for columnar token-efficient cards." },
        wireFormatVersion: { type: "integer", minimum: 1, maximum: 3, description: "Wire format version." },
        maxCards: { type: "integer", description: "Budget: maximum cards." },
        maxTokens: { type: "integer", description: "Budget: maximum estimated tokens." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "slice.refresh": {
    type: "function",
    name: "atlas_slice_refresh",
    description: "Task scoping. Refresh an existing ATLAS slice incrementally when you already have a sliceHandle and knownVersion.",
    parameters: {
      type: "object",
      properties: {
        sliceHandle: { type: "string", description: "ATLAS slice handle." },
        knownVersion: { type: "string", description: "Known slice version." },
      },
      required: ["sliceHandle", "knownVersion"],
      additionalProperties: false,
    },
  },
  "slice.spillover.get": {
    type: "function",
    name: "atlas_slice_spillover_get",
    description: "Task scoping overflow. Fetch overflow symbols only when a truncated slice or delta returned a spilloverHandle.",
    parameters: {
      type: "object",
      properties: {
        spilloverHandle: { type: "string", description: "Spillover handle returned by a truncated slice." },
        cursor: { type: "string", description: "Optional pagination cursor." },
        pageSize: { type: "integer", description: "Page size from 1 to 100." },
      },
      required: ["spilloverHandle"],
      additionalProperties: false,
    },
  },
  "symbol.overview": {
    type: "function",
    name: "atlas_symbol_usages",
    description: "Usage tracing. Return compact call/reference sites for an ATLAS symbolId without hydrating full caller cards.",
    parameters: {
      type: "object",
      properties: {
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Opaque ATLAS symbol ID whose usages should be listed." },
        kind: { type: "array", items: { type: "string", enum: ["calls", "references", "reads", "writes", "uses_type", "imports", "extends", "implements"] }, description: "Optional edge kinds to include." },
        limit: { type: "integer", description: "Maximum usage sites to return." },
        minConfidence: { type: "number", description: "Minimum edge confidence, either 0..1 or 0..100." },
        includeUnresolved: { type: "boolean", description: "Also include unresolved references with the same target name." },
      },
      required: ["symbolId"],
      additionalProperties: false,
    },
  },
  "tree.overview": {
    type: "function",
    name: "atlas_tree_overview",
    description: "Top-level code tree orientation. Returns the root page of the ATLAS containment tree plus the compressed-tree labeled area map. Use tree.branch to drill into a specific branch.",
    parameters: {
      type: "object",
      properties: {
        nodeId: { type: "string", description: "Exact ATLAS tree node id, such as root, dir:src, file:src/run.ts, or a symbol node id." },
        path: { type: "string", description: "Canonical repo-relative file or directory path to focus." },
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Stable ATLAS symbol ID/ref. Duplicated blobs may return multiple tree locations; pass path to disambiguate." },
        refType: { type: "string", enum: ["cluster", "process"], description: "Direct leaf ref lookup type." },
        refId: { type: "string", description: "Cluster/process id for ref lookup." },
        maxDepth: { type: "integer", description: "Descendant depth from focused node(s). Default 1, max 8." },
        limit: { type: "integer", description: "Maximum nodes to return. Default 100, max 500." },
        offset: { type: "integer", description: "Page offset into the focused subtree." },
        includeAggregates: { type: "boolean", description: "Include aggregate counts/raw metrics on each node. Default true." },
        includeTerms: { type: "boolean", description: "Include generated search terms on each node. Default false." },
        includeRefs: { type: "boolean", description: "Include direct cluster/process refs on returned nodes. Default false." },
        includeLatestRun: { type: "boolean", description: "Include latest tree-derived build run metadata. Default true." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "tree.branch": {
    type: "function",
    name: "atlas_tree_walk",
    description: "Walk a code-tree branch. Focus a path, nodeId, symbolId, or cluster/process ref and page through its descendants with aggregate counts and compressed-tree area labels. Structure only (paths, counts, labels — no code content); for per-file skeletons plus a call map over an area, follow with one code.survey call.",
    parameters: {
      type: "object",
      properties: {
        nodeId: { type: "string", description: "Exact ATLAS tree node id, such as root, dir:src, file:src/run.ts, or a symbol node id." },
        path: { type: "string", description: "Canonical repo-relative file or directory path to focus." },
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Stable ATLAS symbol ID/ref. Duplicated blobs may return multiple tree locations; pass path to disambiguate." },
        refType: { type: "string", enum: ["cluster", "process"], description: "Direct leaf ref lookup type." },
        refId: { type: "string", description: "Cluster/process id for ref lookup." },
        maxDepth: { type: "integer", description: "Descendant depth from focused node(s). Default 1, max 8." },
        limit: { type: "integer", description: "Maximum nodes to return. Default 100, max 500." },
        offset: { type: "integer", description: "Page offset into the focused subtree." },
        includeAggregates: { type: "boolean", description: "Include aggregate counts/raw metrics on each node. Default true." },
        includeTerms: { type: "boolean", description: "Include generated search terms on each node. Default false." },
        includeRefs: { type: "boolean", description: "Include direct cluster/process refs on returned nodes. Default false." },
        includeLatestRun: { type: "boolean", description: "Include latest tree-derived build run metadata. Default true." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "tree.scope": {
    type: "function",
    name: "atlas_tree_scope",
    description: "Prefetch-only task scoping. The handoff runs this with the full task text; agents should use tree.expand (seed expansion), tree.branch, and symbol tools instead.",
    parameters: {
      type: "object",
      properties: {
        taskText: { type: "string", description: "Natural-language task, bug, or planning text to score against projected tree terms." },
        taskType: { type: "string", enum: ["debug", "review", "implement", "explain"], description: "Optional task type for test/scope hints." },
        paths: { type: "array", items: { type: "string" }, description: "Repo-relative file or directory seeds." },
        editedFiles: { type: "array", items: { type: "string" }, description: "Known or proposed repo-relative file scope seeds." },
        path: { type: "string", description: "Single repo-relative file or directory seed." },
        symbolIds: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs to use as exact seeds." },
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Single opaque ATLAS symbol ID seed." },
        nodeIds: { type: "array", items: { type: "string" }, description: "Exact tree node ids from tree.overview." },
        refs: {
          type: "array",
          items: {
            type: "object",
            properties: {
              refType: { type: "string", enum: ["cluster", "process"] },
              refId: { type: "string" },
            },
            required: ["refType", "refId"],
            additionalProperties: false,
          },
          description: "Cluster/process refs as weak seeds; broad refs are rejected and reported.",
        },
        refType: { type: "string", enum: ["cluster", "process"], description: "Single ref type." },
        refId: { type: "string", description: "Single cluster/process ref id." },
        maxFiles: { type: "integer", description: "Maximum candidate files returned. Default 40, max 500." },
        maxBranches: { type: "integer", description: "Maximum accepted containment branches. Default 12." },
        branchFileCap: { type: "integer", description: "Maximum files under one accepted branch before it is treated as broad. Default 40." },
        refMatchLimit: { type: "integer", description: "Maximum ref matches to score before treating the ref as broad. Default 50." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "tree.expand": {
    type: "function",
    name: "atlas_tree_grow",
    description: "Grow scope from validated seeds. Expand files/areas you already know matter into surrounding branches, sibling files, tests, and entrypoints, with deterministic scope/risk metrics. Use symbol.card/symbol.overview for symbol identity; use this for file/area breadth.",
    parameters: {
      type: "object",
      properties: {
        paths: { type: "array", items: { type: "string" }, description: "Repo-relative file or directory seeds." },
        editedFiles: { type: "array", items: { type: "string" }, description: "Known or proposed repo-relative file scope seeds." },
        path: { type: "string", description: "Single repo-relative file or directory seed." },
        symbolIds: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs to use as exact seeds." },
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Single opaque ATLAS symbol ID seed." },
        nodeIds: { type: "array", items: { type: "string" }, description: "Exact tree node ids from tree.overview." },
        refs: {
          type: "array",
          items: {
            type: "object",
            properties: {
              refType: { type: "string", enum: ["cluster", "process"] },
              refId: { type: "string" },
            },
            required: ["refType", "refId"],
            additionalProperties: false,
          },
          description: "Cluster/process refs as weak seeds; broad refs are rejected and reported.",
        },
        refType: { type: "string", enum: ["cluster", "process"], description: "Single ref type." },
        refId: { type: "string", description: "Single cluster/process ref id." },
        maxFiles: { type: "integer", description: "Maximum candidate files returned. Default 40, max 500." },
        maxBranches: { type: "integer", description: "Maximum accepted containment branches. Default 12." },
        branchFileCap: { type: "integer", description: "Maximum files under one accepted branch before it is treated as broad. Default 40." },
        refMatchLimit: { type: "integer", description: "Maximum ref matches to score before treating the ref as broad. Default 50." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "edit.plan": {
    type: "function",
    name: "atlas_edit_plan",
    description: "Preview-only edit planning. Produce symbol/file-scoped edit candidates with preconditions before using scoped write tools.",
    parameters: {
      type: "object",
      properties: {
        taskText: { type: "string", description: "Natural-language edit intent." },
        targetSymbols: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs to scope the plan." },
        targetFiles: { type: "array", items: { type: "string" }, description: "Repository-relative files to scope the plan." },
        search: { type: "string", description: "Text/pattern the planned edit expects to find." },
        replace: { type: "string", description: "Replacement text for replace plans." },
        operation: { type: "string", enum: ["replace", "insert", "delete", "inspect"], description: "Planned operation type." },
        maxEdits: { type: "integer", minimum: 1, maximum: 500, description: "Maximum preview edits to return." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "code.skeleton": {
    type: "function",
    name: "atlas_code_get_skeleton",
    description: "Iris Rung 2 (~300 tokens). Fetch a deterministic code skeleton for a file or symbol without full raw bodies.",
    parameters: {
      type: "object",
      properties: {
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Optional opaque ATLAS symbol ID returned by ATLAS. Do not pass a file path here; use file for path-based skeletons." },
        file: { type: "string", description: "Optional relative file path to inspect." },
        exportedOnly: { type: "boolean", description: "Prefer exported symbols only when possible." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "code.survey": {
    type: "function",
    name: "atlas_code_survey",
    description: "Best first call for work that covers an AREA — enumerations, audits, \"every X under Y\", or orienting in several files at once. ONE call returns per-file skeletons plus a call map for a directory or file list, replacing per-file skeleton/lens/window loops and grep-digging, and satisfies card+skeleton evidence for every file it covers. Without symbols: file-level wiring map (which file calls which, counts, one representative site each). With symbols: symbol-level dig restricted to those names' neighborhoods, including unresolved name references (string dispatch grep parity). Boundary rows always show which outside symbols reach in (the doors).",
    parameters: {
      type: "object",
      properties: {
        paths: { type: ["string", "array"], items: { type: "string" }, description: "Repository-relative directory prefix or file path — one string or an array of them, e.g. \"src/billing\" or [\"lib/a.js\", \"lib/b.js\"]. Resolves up to 64 indexed files." },
        symbols: { type: "array", items: { type: "string" }, description: "Optional. Dig terms: restrict the survey to these symbol names' neighborhoods (max 16)." },
        maxFiles: { type: "integer", description: "Optional. Cap on files surveyed. Default 64." },
        sessionId: { type: "string", description: "Optional session namespace for ladder credit (matches other code.* actions)." },
      },
      required: ["paths"],
      additionalProperties: false,
    },
  },
  "code.lens": {
    type: "function",
    name: "atlas_code_get_hot_path",
    description: "Iris Rung 3 (~600 tokens). Fetch identifier-focused code lines with small context windows for an ATLAS symbol or a repo-relative file. AST usages match first; identifiers that only appear inside strings/comments (e.g. dispatch like $action === 'create') return as matchKind \"text\" via identifiersFoundInText, so identifiersMissing means the identifier appears nowhere in the target.",
    parameters: {
      type: "object",
      properties: {
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Opaque ATLAS symbol ID returned by ATLAS. Do not construct this from a file path, symbol name, or file:symbol pair." },
        file: { type: "string", description: "Repository-relative file path fallback when you have a file but not an opaque symbolId." },
        identifiersToFind: { type: "array", items: { type: "string" }, description: "Identifiers to match. Prefer a JSON array; legacy scalar strings are normalized." },
        contextLines: { type: "integer", description: "Context lines around each match." },
      },
      required: ["identifiersToFind"],
      additionalProperties: false,
    },
  },
  "code.window": {
    type: "function",
    name: "atlas_code_need_window",
    description: "Iris Rung 4 (~2000 tokens). Request a policy-gated raw code window for one ATLAS symbol or file only after card, skeleton, or hot-path evidence is insufficient. Prefer expectedLines as a JSON number and identifiersToFind as a JSON array; legacy strings are normalized.",
    parameters: {
      type: "object",
      properties: {
        symbolId: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN, description: "Opaque ATLAS symbol ID from symbol.search, symbol.card, slice.build, skeleton, or hot path results. Do not pass a file path, symbol name, or file:symbol pair here." },
        file: { type: "string", description: "Repository-relative file path fallback when you have a file but not an opaque symbolId." },
        reason: { type: "string", description: "Required proof-of-need justification for raw window escalation." },
        identifiersToFind: { type: "array", items: { type: "string" }, description: "Identifiers expected in the requested window, for example [\"generateMusic\",\"json_decode\"]. Prefer a JSON array; legacy scalar strings are normalized." },
        expectedLines: { type: "integer", description: "Approximate line count. Prefer a JSON number, for example 40; legacy numeric strings are normalized." },
        maxTokens: { type: "integer", description: "Max tokens budget for the raw window." },
      },
      required: ["reason", "expectedLines", "identifiersToFind"],
      additionalProperties: false,
    },
  },
  "context": {
    type: "function",
    name: "atlas_context",
    description: "Task-shaped discovery. Retrieve generated ATLAS context for explain, debug, review, or implement work before broad native reads.",
    parameters: {
      type: "object",
      properties: {
        taskText: { type: "string", description: "Task description for ATLAS context retrieval." },
        taskType: { type: "string", description: "Task type such as debug, review, implement, or explain." },
        contextMode: { type: "string", description: "Context breadth mode: precise or broad." },
        focusSymbols: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Optional opaque ATLAS symbol IDs returned by ATLAS results." },
        focusPaths: { type: "array", items: { type: "string" }, description: "Optional file paths to focus." },
        maxTokens: { type: "integer", description: "Budget: maximum generated context tokens." },
        maxActions: { type: "integer", description: "Budget: maximum retrieval actions." },
      },
      required: ["taskText"],
      additionalProperties: false,
    },
  },
  "context.summary": {
    type: "function",
    name: "atlas_context_summary",
    description: "Task-shaped summary. Retrieve compact ATLAS context with an answer, evidence list, quality hints, and next action guidance.",
    parameters: {
      type: "object",
      properties: {
        taskText: { type: "string", description: "Task description for ATLAS context retrieval." },
        taskType: { type: "string", description: "Task type such as debug, review, implement, or explain." },
        contextMode: { type: "string", description: "Context breadth mode: precise or broad." },
        focusSymbols: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Optional opaque ATLAS symbol IDs returned by ATLAS results." },
        focusPaths: { type: "array", items: { type: "string" }, description: "Optional file paths to focus." },
        maxTokens: { type: "integer", description: "Budget: maximum generated context tokens." },
        maxActions: { type: "integer", description: "Budget: maximum retrieval actions." },
        maxEvidence: { type: "integer", description: "Maximum evidence items to include in the compact summary." },
        includeCards: { type: "boolean", description: "Include compact symbol cards beside the summary evidence." },
      },
      required: ["taskText"],
      additionalProperties: false,
    },
  },
  "agent.feedback": {
    type: "function",
    name: "atlas_agent_feedback",
    description: "Record which symbols were useful or missing to improve future ATLAS context quality.",
    parameters: {
      type: "object",
      properties: {
        sliceHandle: { type: "string", description: "Slice handle used during the task." },
        usefulSymbols: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs that were helpful. Non-ID placeholders are accepted for diagnostics but do not improve symbol ranking." },
        missingSymbols: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Opaque ATLAS symbol IDs that were missing or needed. Non-ID placeholders are accepted for diagnostics but do not improve symbol ranking." },
        taskType: { type: "string", description: "Task type such as debug, review, implement, or explain." },
        taskText: { type: "string", description: "Short description of the task context." },
        taskTags: { type: "array", items: { type: "string" }, description: "Short outcome/context tags such as role:dev or outcome:succeeded." },
      },
      required: ["sliceHandle"],
      additionalProperties: false,
    },
  },
  "agent.feedback.query": {
    type: "function",
    name: "atlas_agent_feedback_query",
    description: "Query ATLAS feedback aggregates for offline tuning and relevance diagnostics.",
    parameters: {
      type: "object",
      properties: {
        since: { type: "string", description: "Optional ISO timestamp lower bound." },
        limit: { type: "integer", description: "Maximum aggregate rows to return." },
        taskType: { type: "string", description: "Optional task type filter such as debug, review, implement, or explain." },
        halfLifeDays: { type: "number", description: "Optional recency decay half-life in days for weighted aggregates." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "review.delta": {
    type: "function",
    name: "atlas_delta_get",
    description: "Review evidence. Fetch an ATLAS semantic diff and blast-radius delta between two ledger versions.",
    parameters: {
      type: "object",
      properties: {
        fromVersion: { type: "string", description: "Base version ID." },
        toVersion: { type: "string", description: "Head version ID." },
        maxCards: { type: "integer", description: "Budget: maximum cards." },
        maxTokens: { type: "integer", description: "Budget: maximum estimated tokens." },
      },
      required: ["fromVersion", "toVersion"],
      additionalProperties: false,
    },
  },
  "review.analyze": {
    type: "function",
    name: "atlas_pr_risk_analyze",
    description: "Review evidence. Run ATLAS PR risk analysis with scored findings, blast-radius evidence, and test recommendations.",
    parameters: {
      type: "object",
      properties: {
        fromVersion: { type: "string", description: "Base version ID." },
        toVersion: { type: "string", description: "Head version ID." },
        riskThreshold: { type: "number", description: "Optional risk threshold (0-100)." },
      },
      required: ["fromVersion", "toVersion"],
      additionalProperties: false,
    },
  },
  "review.risk": {
    type: "function",
    name: "atlas_pr_risk",
    description: "Assessor-first review. Fetch ATLAS semantic delta, blast radius, risk findings, and test recommendations in one combined call.",
    parameters: {
      type: "object",
      properties: {
        fromVersion: { type: "string", description: "Base version ID." },
        toVersion: { type: "string", description: "Head version ID." },
        maxCards: { type: "integer", description: "Budget for the semantic delta." },
        maxTokens: { type: "integer", description: "Token budget for the semantic delta." },
        riskThreshold: { type: "number", description: "Optional risk threshold (0-100)." },
      },
      required: ["fromVersion", "toVersion"],
      additionalProperties: false,
    },
  },
  "memory.store": {
    type: "function",
    name: "atlas_memory_store",
    description: "Memory. Store one rare, verified repo lesson linked to exact symbols/files. Skip the write when an anchor already has sufficient memory or the finding is obvious from code. Title max 120 chars; content max 1200 chars.",
    parameters: {
      type: "object",
      properties: {
        title: { type: "string", description: "Short memory title, max 120 chars." },
        content: { type: "string", description: "Memory content, max 1200 chars. Capture why the decision/context matters." },
        domains: { type: "array", items: { type: "string", enum: ["ux", "schema", "security", "performance"] }, description: "Optional domain tags for scoped retrieval. Omit unless the memory's PRIMARY concern is one of these (omitting files it under the general catch-all)." },
        symbolIds: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Optional linked ATLAS symbol IDs." },
        fileRelPaths: { type: "array", items: { type: "string" }, description: "Optional linked repo-relative files." },
        memoryId: { type: "string", description: "Optional existing memory ID to update." },
      },
      required: ["title", "content"],
      additionalProperties: false,
    },
  },
  "memory.feedback": {
    type: "function",
    name: "atlas_memory_feedback",
    description: "Memory. Issue positive or actionable negative feedback for an existing memory after you actually used or checked it. Do not call merely because a memory exists or was unhelpful.",
    parameters: {
      type: "object",
      properties: {
        memoryId: { type: "string", description: "Memory ID returned by memory.get." },
        verdict: { type: "string", enum: ["used", "stale", "wrong", "duplicate"], description: "Role-relative verdict. Use 'used' only when the memory materially informed the work; use negative verdicts only with evidence. Do not call feedback for merely unhelpful memories." },
        detail: { type: "string", description: "Optional short evidence note (one sentence)." },
      },
      required: ["memoryId", "verdict"],
      additionalProperties: false,
    },
  },
  "memory.surface": {
    type: "function",
    name: "atlas_memory_surface",
    description: "Memory. Probe exact symbols/files and return only which anchors have attached memories. No memory IDs, no bodies, no fuzzy search.",
    parameters: {
      type: "object",
      properties: {
        symbolIds: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Symbols to probe." },
        fileRelPaths: { type: "array", items: { type: "string" }, description: "Files to probe." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "memory.get": {
    type: "function",
    name: "atlas_memory_get",
    description: "Memory. Fetch full memory bodies grouped by exact symbol/file anchors, normally only for anchors returned by memory.surface or shown in handoff prefetch.",
    parameters: {
      type: "object",
      properties: {
        symbolIds: { type: "array", items: { type: "string", pattern: ATLAS_SYMBOL_ID_PATTERN }, description: "Symbols whose attached memories should be fetched." },
        fileRelPaths: { type: "array", items: { type: "string" }, description: "Files whose attached memories should be fetched." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "policy.get": {
    type: "function",
    name: "atlas_policy_get",
    description: "Policy. Fetch native ATLAS v2 policy for the current repository.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional repository identifier; defaults to the current ATLAS repo." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "policy.set": {
    type: "function",
    name: "atlas_policy_set",
    description: "Policy. Patch native ATLAS v2 policy values such as code-window caps, memory enablement, and runtime enablement.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional repository identifier; defaults to the current ATLAS repo." },
        policyPatch: {
          type: "object",
          properties: {
            maxWindowLines: { type: "integer" },
            maxWindowTokens: { type: "integer" },
            requireIdentifiers: { type: "boolean" },
            allowBreakGlass: { type: "boolean" },
            defaultMinCallConfidence: { type: "number" },
            defaultDenyRaw: { type: "boolean" },
            memoryEnabled: { type: "boolean" },
            runtimeEnabled: { type: "boolean" },
            budgetCaps: {
              type: "object",
              properties: {
                maxCards: { type: "integer" },
                maxEstimatedTokens: { type: "integer" },
              },
              additionalProperties: false,
            },
          },
          additionalProperties: false,
        },
      },
      required: ["policyPatch"],
      additionalProperties: false,
    },
  },
  "usage.stats": {
    type: "function",
    name: "atlas_usage_stats",
    description: "Usage. Report native ATLAS v2 action counts, latency, and estimated token savings from ledger usage events.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional repository identifier; defaults to the current ATLAS repo." },
        scope: { type: "string", enum: ["session", "history", "both"], description: "Stats scope." },
        since: { type: "string", description: "Optional ISO timestamp lower bound." },
        limit: { type: "integer", description: "Maximum history rows." },
        aggregateLimit: { type: "integer", description: "Maximum rows scanned for aggregate totals. Default: 1000." },
        persist: { type: "boolean", description: "Accepted for compatibility; native v2 records events continuously." },
      },
      required: [],
      additionalProperties: false,
    },
  },
  "runtime.execute": {
    type: "function",
    name: "atlas_runtime_execute",
    description: "Runtime. Execute a policy-gated command inside the repository with timeout, output caps, redaction, and optional output artifact storage.",
    parameters: {
      type: "object",
      properties: {
        repoId: { type: "string", description: "Optional repository identifier; policy is scoped by repo." },
        runtime: { type: "string", enum: ["node", "python", "python3", "shell"], description: "Runtime family to execute." },
        executable: { type: "string", description: "Optional PATH command override. Paths are denied." },
        args: { type: "array", items: { type: "string" }, description: "Arguments passed directly to the executable without a shell." },
        code: { type: "string", description: "Optional code snippet written to a temporary ATLAS artifact file and executed." },
        relativeCwd: { type: "string", description: "Working directory relative to repo root; must not escape the repo." },
        timeoutMs: { type: "integer", description: "Execution timeout in milliseconds." },
        queryTerms: { type: "array", items: { type: "string" }, description: "Terms for intent-mode output excerpts." },
        maxResponseLines: { type: "integer", description: "Maximum lines in summary mode." },
        persistOutput: { type: "boolean", description: "Persist full redacted output for runtime.queryOutput. Defaults true." },
        outputMode: { type: "string", enum: ["minimal", "summary", "intent"], description: "Response verbosity. Defaults to minimal." },
      },
      required: ["runtime"],
      additionalProperties: false,
    },
  },
  "runtime.queryOutput": {
    type: "function",
    name: "atlas_runtime_query_output",
    description: "Runtime. Query persisted runtime output artifacts by keyword without re-running the command.",
    parameters: {
      type: "object",
      properties: {
        artifactHandle: { type: "string", description: "Artifact handle from runtime.execute." },
        queryTerms: { type: "array", items: { type: "string" }, description: "Keywords to search for." },
        maxExcerpts: { type: "integer", description: "Maximum excerpt windows to return." },
        contextLines: { type: "integer", description: "Context lines around each match." },
        stream: { type: "string", enum: ["stdout", "stderr", "both"], description: "Output stream to search." },
      },
      required: ["artifactHandle", "queryTerms"],
      additionalProperties: false,
    },
  },
  "scip.ingest": {
    type: "function",
    name: "atlas_scip_ingest",
    description: "SCIP. Ingest a prebuilt .scip index into the native ATLAS v2 ledger and rebuild the materialized view.",
    parameters: {
      type: "object",
      properties: {
        indexPath: { type: "string", description: "Path to the .scip index, absolute or relative to repo root." },
        dryRun: { type: "boolean", description: "Decode and summarize without mutating the ledger." },
        force: { type: "boolean", description: "Force reingest even when this fileset was already consumed." },
        branch: { type: "string", description: "Ledger branch to append path deltas to. Defaults to the active branch." },
      },
      required: ["indexPath"],
      additionalProperties: false,
    },
  },
  "file.read": {
    type: "function",
    name: "atlas_file_read",
    description: "Targeted non-indexed file read. Read markdown, configs, templates, JSON/YAML, or data files through ATLAS with line range, search, or JSON path targeting; use card/skeleton/hot-path for indexed source code first.",
    parameters: {
      type: "object",
      properties: {
        filePath: { type: "string", description: "File path relative to the repository root." },
        maxBytes: { type: "integer", description: "Maximum bytes to read." },
        offset: { type: "integer", description: "0-based starting line number." },
        limit: { type: "integer", description: "Maximum lines to return." },
        search: { type: "string", description: "Case-insensitive regex pattern to search for." },
        searchContext: { type: "integer", description: "Context lines around each search match." },
        jsonPath: { type: "string", description: "Dot-separated path to extract from JSON/YAML files." },
      },
      required: ["filePath"],
      additionalProperties: false,
    },
  },
  "file.write": {
    type: "function",
    name: "atlas_file_write",
    description: "Write non-indexed repository files through ATLAS using exactly one write mode.",
    parameters: {
      type: "object",
      properties: {
        filePath: { type: "string", description: "File path relative to the repository root." },
        content: { type: "string", description: "Full file content for create/overwrite mode." },
        replaceLines: {
          type: "object",
          properties: {
            start: { type: "integer", description: "0-based inclusive start line." },
            end: { type: "integer", description: "0-based exclusive end line." },
            content: { type: "string", description: "Replacement content." },
          },
          required: ["start", "end", "content"],
          additionalProperties: false,
        },
        replacePattern: {
          type: "object",
          properties: {
            pattern: { type: "string", description: "Regex pattern to find." },
            replacement: { type: "string", description: "Replacement text." },
            global: { type: "boolean", description: "Replace all occurrences." },
          },
          required: ["pattern", "replacement"],
          additionalProperties: false,
        },
        jsonPath: { type: "string", description: "Dot-separated path to update in JSON/YAML." },
        jsonValue: { description: "Value to write when jsonPath is used." },
        insertAt: {
          type: "object",
          properties: {
            line: { type: "integer", description: "0-based line number to insert at." },
            content: { type: "string", description: "Content to insert." },
          },
          required: ["line", "content"],
          additionalProperties: false,
        },
        append: { type: "string", description: "Content to append to the file." },
        createBackup: { type: "boolean", description: "Create a .bak backup before modifying." },
        createIfMissing: { type: "boolean", description: "Create the file if it does not exist." },
      },
      required: ["filePath"],
      additionalProperties: false,
    },
  },
});
