// lib/domains/providers/functions/codex/cli-spawn.js

import fs from "fs";
import os from "os";
import path from "path";
import { normalizeConfiguredAuthMode } from "./auth.js";
import { _toTomlLiteral } from "./config-format.js";
import { normalizeCodexSessionHandle } from "./session.js";

export function makeTempOutputFile() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "posse-codex-"));
  return {
    dir,
    file: path.join(dir, "last-message.txt"),
  };
}

export function cleanupTempDir(dir) {
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch {
    // Best-effort cleanup only.
  }
}

function cleanupConfigSpillDirAsync(dir) {
  if (!dir) return Promise.resolve();
  const parent = path.dirname(dir);
  const tombstone = path.join(
    parent,
    `${path.basename(dir)}.cleanup-${process.pid}-${Date.now()}`,
  );
  let target = dir;
  try {
    fs.renameSync(dir, tombstone);
    target = tombstone;
  } catch (error) {
    if (error?.code === "ENOENT") return Promise.resolve();
  }
  return fs.promises.rm(target, { recursive: true, force: true }).catch(() => {});
}

function cleanupStaleConfigSpills(parent) {
  void fs.promises.readdir(parent, { withFileTypes: true }).then((entries) => Promise.all(
    entries
      .filter((entry) => entry.isDirectory() && entry.name.includes(".cleanup-"))
      .map((entry) => fs.promises.rm(path.join(parent, entry.name), { recursive: true, force: true }).catch(() => {})),
  )).catch(() => {});
}

const CODEX_CONFIG_ARG_SPILL_SINGLE_LIMIT = 6000;
const CODEX_CONFIG_ARG_SPILL_TOTAL_LIMIT = 12000;

function getCodexHomeFromEnv(env = process.env) {
  const configured = String(env?.CODEX_HOME || "").trim();
  return configured ? path.resolve(configured) : path.join(os.homedir(), ".codex");
}

export function shouldSpillCodexConfigOverrides(configOverrides = [], {
  platform = process.platform,
} = {}) {
  if (platform !== "win32") return false;
  const values = (configOverrides || []).map((entry) => String(entry || ""));
  const totalLength = values.reduce((sum, entry) => sum + entry.length, 0);
  return values.some((entry) => entry.length > CODEX_CONFIG_ARG_SPILL_SINGLE_LIMIT)
    || totalLength > CODEX_CONFIG_ARG_SPILL_TOTAL_LIMIT;
}

function bestEffortChmod(filePath, mode) {
  try { fs.chmodSync(filePath, mode); } catch { /* Windows/best-effort */ }
}

export function prepareCodexConfigForSpawn(configOverrides = [], {
  env = process.env,
  platform = process.platform,
  tempParent = null,
  authMode = "oauth",
} = {}) {
  const overrides = (configOverrides || []).filter(Boolean).map((entry) => String(entry));
  if (!shouldSpillCodexConfigOverrides(overrides, { platform })) {
    return {
      configOverrides: overrides,
      codexHome: null,
      cleanup: () => {},
      cleanupAsync: async () => {},
      spilled: false,
    };
  }

  const sourceHome = getCodexHomeFromEnv(env);
  const parent = tempParent || path.join(sourceHome, ".posse-run-homes");
  fs.mkdirSync(parent, { recursive: true, mode: 0o700 });
  cleanupStaleConfigSpills(parent);
  bestEffortChmod(parent, 0o700);
  const codexHome = fs.mkdtempSync(path.join(parent, "codex-"));
  bestEffortChmod(codexHome, 0o700);
  const configPath = path.join(codexHome, "config.toml");
  fs.writeFileSync(
    configPath,
    [
      "# Generated by Posse for one Codex provider invocation.",
      "# Large config overrides live here to avoid Windows command-line limits.",
      ...overrides,
      "",
    ].join("\n"),
    "utf8",
  );
  bestEffortChmod(configPath, 0o600);

  const sourceAuth = path.join(sourceHome, "auth.json");
  const targetAuth = path.join(codexHome, "auth.json");
  try {
    if (normalizeConfiguredAuthMode(authMode) === "oauth" && fs.existsSync(sourceAuth)) {
      fs.copyFileSync(sourceAuth, targetAuth);
      bestEffortChmod(targetAuth, 0o600);
    }
  } catch {
    // Provider readiness will surface auth problems; spilling config must not
    // mask the original call path with a best-effort copy failure.
  }

  return {
    configOverrides: [],
    codexHome,
    cleanup: () => cleanupTempDir(codexHome),
    cleanupAsync: () => cleanupConfigSpillDirAsync(codexHome),
    spilled: true,
  };
}

export function buildCodexExecArgs({
  codexArgs = [],
  outputFile,
  workingDir,
  allowWrite = false,
  modelToUse = null,
  reasoningEffort = null,
  configOverrides = [],
  forceReadOnlySandbox = false,
  priorSessionHandle = null,
} = {}) {
  const sandboxMode = (allowWrite && !forceReadOnlySandbox) ? "workspace-write" : "read-only";
  const resumeHandle = normalizeCodexSessionHandle(priorSessionHandle);
  const args = [
    ...codexArgs,
    "exec",
    ...(resumeHandle ? ["resume"] : []),
    "--json",
    "--output-last-message", outputFile,
    "--skip-git-repo-check",
    "--ignore-rules",
    // Non-interactive exec: failures return to the model instead of
    // auto-cancelling MCP tool calls as "user cancelled". Sandbox still
    // gates apply_patch/shell writes, so MCP remains the only write path.
    // `codex exec` has no --ask-for-approval flag; use the config override.
    "-c", 'approval_policy="never"',
    "-c", `sandbox_mode=${_toTomlLiteral(sandboxMode)}`,
  ];

  if (!resumeHandle) {
    args.push("--cd", workingDir, "--sandbox", sandboxMode);
  }

  if (modelToUse) {
    args.push("--model", modelToUse);
  }

  const normalizedReasoningEffort = String(reasoningEffort || "").trim().toLowerCase();
  if (["low", "medium", "high"].includes(normalizedReasoningEffort)) {
    args.push("-c", `model_reasoning_effort=${_toTomlLiteral(normalizedReasoningEffort)}`);
  }

  for (const override of (configOverrides || [])) {
    if (!override) continue;
    args.push("-c", override);
  }

  if (resumeHandle) {
    args.push(resumeHandle);
  }
  args.push("-");
  return args;
}

export function __testBuildCodexExecArgs(options) {
  return buildCodexExecArgs(options);
}

function isPathInsideOrEqual(candidate, root) {
  const relative = path.relative(path.resolve(root), path.resolve(candidate));
  return relative === "" || (!!relative && !relative.startsWith("..") && !path.isAbsolute(relative));
}

export function collectCodexExtraDirs({
  workingDir,
  scopedFiles = [],
  createFiles = [],
  deleteFiles = [],
  createRoots = [],
  readRoots = [],
  fsImpl = fs,
} = {}) {
  const extraDirs = new Set();
  for (const p of [...(scopedFiles || []), ...(createFiles || []), ...(createRoots || []), ...(readRoots || [])]) {
    if (!p) continue;
    const abs = path.isAbsolute(p) ? p : path.resolve(workingDir, p);
    const dir = fsImpl.existsSync(abs) && fsImpl.statSync(abs).isDirectory() ? abs : path.dirname(abs);
    if (!isPathInsideOrEqual(dir, workingDir)) extraDirs.add(dir);
  }
  return extraDirs;
}

export function __testCollectCodexExtraDirs(options) {
  return [...collectCodexExtraDirs(options)].sort();
}
